// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiMZQinPnvkoZZUm8GR15izalxYrUWC4',
    appId: '1:950318795759:web:ae2e07853f1e647d7f841a',
    messagingSenderId: '950318795759',
    projectId: 'ecommerce-601cf',
    authDomain: 'ecommerce-601cf.firebaseapp.com',
    storageBucket: 'ecommerce-601cf.appspot.com',
    measurementId: 'G-4VLH352WN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VFO-nNPT8xRC8PuLf7QM4ORHlt8pzt0',
    appId: '1:950318795759:android:9860539c16ebfc347f841a',
    messagingSenderId: '950318795759',
    projectId: 'ecommerce-601cf',
    storageBucket: 'ecommerce-601cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBeQRnDAj_oK2NlNHpuqkXWSouAEdzIWc',
    appId: '1:950318795759:ios:6670c89f70e17a3e7f841a',
    messagingSenderId: '950318795759',
    projectId: 'ecommerce-601cf',
    storageBucket: 'ecommerce-601cf.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBeQRnDAj_oK2NlNHpuqkXWSouAEdzIWc',
    appId: '1:950318795759:ios:11316252822bf8187f841a',
    messagingSenderId: '950318795759',
    projectId: 'ecommerce-601cf',
    storageBucket: 'ecommerce-601cf.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
